# Generated by Django 4.1 on 2022-08-27 07:57

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia')], default='LT', max_length=50, verbose_name='Country')),
                ('IBAN', models.CharField(default=User.models.Account.create_random_iban, max_length=16)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
