# Generated by Django 4.0.6 on 2022-09-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('senders_account_currency', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('sender_IBAN', models.CharField(max_length=16)),
                ('receiver_IBAN', models.CharField(max_length=100)),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
