# Generated by Django 4.0.6 on 2022-08-22 17:02

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='IBAN',
            field=models.CharField(default=User.models.Account.create_random_iban, max_length=16),
        ),
    ]
