# Generated by Django 4.0.6 on 2022-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_account_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
