# Generated by Django 4.0.6 on 2022-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=100, null=True)),
                ('senders_account_currency', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('recipients_name', models.CharField(max_length=100)),
                ('recipients_account_number', models.CharField(max_length=16)),
                ('recipients_account_currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_IBAN', models.CharField(default=0, max_length=100)),
                ('sender_FULLNAME', models.CharField(default=0, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60)),
                ('receiver_IBAN', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
