# Generated by Django 4.1 on 2022-08-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=100, null=True)),
                ('senders_account_currency', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('recipients_name', models.CharField(max_length=100)),
                ('recipients_account_number', models.IntegerField()),
                ('recipients_account_currency', models.CharField(max_length=100)),
            ],
        ),
    ]
