# Generated by Django 4.1 on 2022-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipients_account_number',
            field=models.BigIntegerField(),
        ),
    ]
