# Generated by Django 4.1 on 2022-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_alter_transaction_recipients_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipients_account_number',
            field=models.CharField(max_length=16),
        ),
    ]
