# Generated by Django 4.0.6 on 2022-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_list',
            name='receiver_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
