# Generated by Django 4.1 on 2022-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_alter_transaction_recipients_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
