# Generated by Django 4.1 on 2022-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
