# Generated by Django 4.1 on 2022-08-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='senders_name',
            field=models.CharField(max_length=100),
        ),
    ]
