# Generated by Django 4.1 on 2022-08-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_remove_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='senders_name',
        ),
    ]
