# Generated by Django 4.1 on 2022-08-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_remove_transaction_senders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='senders_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
